name: Android CICD PR

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Clean build
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: clean build
        run: ./gradlew clean build
        env:
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
